export const objectArray = [
  { value: "person", label: "Person" },
  { value: "bicycle", label: "Bicycle" },
  { value: "car", label: "Car" },
  { value: "motorbike", label: "Motorbike" },
  { value: "aeroplane", label: "Aeroplane" },
  { value: "bus", label: "Bus" },
  { value: "train", label: "Train" },
  { value: "truck", label: "Truck" },
  { value: "boat", label: "Boat" },
  { value: "traffic light", label: "Traffic light" },
  { value: "fire hydrant", label: "Fire hydrant" },
  { value: "stop sign", label: "Stop sign" },
  { value: "parking meter", label: "Parking meter" },
  { value: "bench", label: "Bench" },
  { value: "bird", label: "Bird" },
  { value: "cat", label: "Cat" },
  { value: "dog", label: "Dog" },
  { value: "horse", label: "Horse" },
  { value: "sheep", label: "Sheep" },
  { value: "cow", label: "Cow" },
  { value: "elephant", label: "Elephant" },
  { value: "bear", label: "Bear" },
  { value: "zebra", label: "Zebra" },
  { value: "giraffe", label: "Giraffe" },
  { value: "backpack", label: "Backpack" },
  { value: "umbrella", label: "Umbrella" },
  { value: "handbag", label: "Handbag" },
  { value: "tie", label: "Tie" },
  { value: "suitcase", label: "Suitcase" },
  { value: "frisbee", label: "Frisbee" },
  { value: "skis", label: "Skis" },
  { value: "snowboard", label: "Snowboard" },
  { value: "sports ball", label: "Sports ball" },
  { value: "kite", label: "Kite" },
  { value: "baseball bat", label: "Baseball bat" },
  { value: "baseball glove", label: "Baseball glove" },
  { value: "skateboard", label: "Skateboard" },
  { value: "surfboard", label: "Surfboard" },
  { value: "tennis racket", label: "Tennis racket" },
  { value: "bottle", label: "Bottle" },
  { value: "wine glass", label: "Wine glass" },
  { value: "cup", label: "Cup" },
  { value: "fork", label: "Fork" },
  { value: "knife", label: "Knife" },
  { value: "spoon", label: "Spoon" },
  { value: "bowl", label: "Bowl" },
  { value: "banana", label: "Banana" },
  { value: "apple", label: "Apple" },
  { value: "sandwich", label: "Sandwich" },
  { value: "orange", label: "Orange" },
  { value: "broccoli", label: "Broccoli" },
  { value: "carrot", label: "Carrot" },
  { value: "hot dog", label: "Hot dog" },
  { value: "pizza", label: "Pizza" },
  { value: "donut", label: "Donut" },
  { value: "cake", label: "Cake" },
  { value: "chair", label: "Chair" },
  { value: "sofa", label: "Sofa" },
  { value: "pottedplant", label: "Pottedplant" },
  { value: "bed", label: "Bed" },
  { value: "diningtable", label: "Diningtable" },
  { value: "toilet", label: "Toilet" },
  { value: "tvmonitor", label: "Tvmonitor" },
  { value: "laptop", label: "Laptop" },
  { value: "mouse", label: "Mouse" },
  { value: "remote", label: "Remote" },
  { value: "keyboard", label: "Keyboard" },
  { value: "cell phone", label: "Cell phone" },
  { value: "microwave", label: "Microwave" },
  { value: "oven", label: "Oven" },
  { value: "toaster", label: "Toaster" },
  { value: "sink", label: "Sink" },
  { value: "refrigerator", label: "Refrigerator" },
  { value: "book", label: "Book" },
  { value: "clock", label: "Clock" },
  { value: "vase", label: "Vase" },
  { value: "scissors", label: "Scissors" },
  { value: "teddy bear", label: "Teddy bear" },
  { value: "hair drier", label: "Hair drier" },
  { value: "toothbrush", label: "Toothbrush" }
];
